file_format: "1"
id: lily58_enc
name: Lily58_enc
type: shield
url: https://github.com/orvisevans/Lily58-Glow-Enc
requires: [pro_micro]
features:
  - keys
  - encoder
siblings:
  - lily58_enc_left
  - lily58_enc_right
